=head1 NAME

B<db2omf> - utility to extract OMF meta-data from DocBook documents.

=head1 SYNOPSIS

B<db2omf> [I<OPTION>] [I<FILE>]

=head1 DESCRIPTION

B<db2omf> extracts OMF meta-data from a DocBook document and writes it to
a file in SGML format.

=head1 OPTIONS

B<-o> I<filename> write to the specified file.

=head1 BUGS

None currently known. Please report bugs to the author at:

<gferg@metalab.unc.edu>.

=head1 NOTES

B<db2omf> was developed as a project of the Linux Documentation Project.
It was originally written to create OMF files for submission to
the ScrollKeeper system, the standard documentation meta-data database
in many Linux distributions.

=head1 SEE ALSO

See the home page of the Linux Documentation Project,
http://www.tldp.org for updates and more information. Also see the home
page for OMF, http://www.ibiblio.org/osrt/omf/.

=head1 AUTHOR

This man page was written by David C. Merrill, david -AT- lupercalia.net.

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.1 or any later
version published by the Free Software Foundation; with no Invariant Sections,
no Front-Cover Texts and no Back-Cover Texts.

=cut

