[[chap_02]]
Title of second chapter
-----------------------

________________________________
What we will do in this chapter:

* stuff
* more stuff
* talk about other stuff
* play with stuff
________________________________

[[sect_02_01]]
Section1 title
--------------

[[sect_02_01_01]]
Section2 title
~~~~~~~~~~~~~~

[[sect_02_01_01_01]]
Section3 title
^^^^^^^^^^^^^^

Intro

1.  Summing up a few things
2.  in a list
3.  where items are numbered

Explanations

[[sect_02_01_01_01]]
Section3 title
^^^^^^^^^^^^^^

Other explanation

* Summing up a few things
* in a list
* where items are not numbered

And discussion

[[sect_02_01_02]]
Section2 title
~~~~~~~~~~~~~~

Showing a picture in text:

image:your_images_dir/image.eps[image]

PNG is for on-line browsing, EPS for printing. `gimp` and/or `convert`
will do the trick, starting from about any source format.

[[sect_02_02]]
Section1 title
--------------

[[sect_02_02_01]]
Section2 title
~~~~~~~~~~~~~~

This is a table with two colums:

.Table title
[cols=",",options="header",]
|=======================================
|first colum header |second colum header
|item |meaning
|item |meaning
|item |meaning
|=======================================

[[sect_02_02_02]]
Section2 title
~~~~~~~~~~~~~~

This is a link to the first section of the first chapter:
link:#sect_01_01[???].

This is an external link: http://www.somewhere.org[].

This is also http://www.somewhere.org[an external link], only here you
don't see the URL.
