Introduction
------------

[[intro_01]]
Why was this document written?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Some explanations.

[[intro_02]]
Audience
~~~~~~~~

Explain for whom it has been written.

[[intro_03]]
New versions of this doc
~~~~~~~~~~~~~~~~~~~~~~~~

Point to http://somewhere.org[the latest version] of this document.

[[intro_04]]
Revision History
~~~~~~~~~~~~~~~~

1.2 2003-02-28 MG More stuff you changed. 1.1 2003-01-22 MG Stuff you
changed. 1.0 2002-12-29 MG Initial release for TLDP

[[intro_05]]
Contributions
~~~~~~~~~~~~~

Thank people who helped realizing this doc.

[[intro_06]]
Feedback
~~~~~~~~

Missing information, missing links, missing characters? Mail it to the
maintainer of this document: you@your.domain

[[intro_07]]
Copyright information
~~~~~~~~~~~~~~~~~~~~~

Copyright 2002 Your_first_name Your_last_name.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with no Front-Cover Texts and no Back-Cover Texts. A
copy of the license is included in link:#app4[???] entitled ``GNU Free
Documentation License''.

Read http://www.fsf.org/gnu/manifesto.html[The GNU Manifesto] if you
want to know why this license was chosen for this book.

The author and publisher have made every effort in the preparation of
this book to ensure the accuracy of the information. However, the
information contained in this book is offered without warranty, either
express or implied. Neither the author nor the publisher nor any dealer
or distributor will be held liable for any damages caused or alleged to
be caused either directly or indirectly by this book.

The logos, trademarks and symbols used in this book are the properties
of their respective owners.

[[intro_08]]
What do you need?
~~~~~~~~~~~~~~~~~

List requirements: materials, knowledge.

[[intro_09]]
Conventions used in this document
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following typographic and usage conventions occur in this text:

.Typographic and usage conventions
[cols=",",options="header",]
|=======================================================================
|Text type |Meaning
|``Quoted text'' |Quotes from people, quoted computer output.

a|
-------------
terminal view
-------------

 |Literal computer input and output captured from the terminal, usually
rendered with a light grey background.

|`command` |Name of a command that can be entered on the command line.

|`VARIABLE` |Name of a variable or pointer to content of a variable, as
in `$VARNAME`.

|`option` |Option to a command, as in ``the `-a` option to the `ls`
command''.

|`argument` |Argument to a command, as in ``read `man ls`''.

|`command options 
arguments` |Command synopsis or general usage, on a separated line.

|`filename` |Name of a file or directory, for example ``Change to the
`/usr/bin` directory.''

|Key |Keys to hit on the keyboard, such as ``type Q to quit''.

|Button |Graphical button to click, like the OK button.

|Menu > Choice |Choice to select from a graphical menu, for instance:
``Select Help > About Mozilla in your browser.''

|_Terminology_ |Important term or concept: ``The Linux _kernel_ is the
heart of the system.''

|See link:#chap_01[???] |link to related subject within this guide.

|http://tille.soti.org[The author] |Clickable link to an external web
resource.
|=======================================================================

[[intro_10]]
Organization of this document
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

List chapters (and optionally, appendices) with a short content for each
(only for longer docs).

* link:#chap_01[???]: short description.
* link:#chap_02[???]: short description.
* link:#chap_03[???]: short description.
* link:#chap_04[???]: short description.
* link:#chap_05[???]: short description.

CHAP1 CHAP2 APP1 GLOSS
