#!/bin/sh
#
# This script runs the passed command line 10 times and reports the results.
# 

echo `date` > /tmp/lampadas-timer

for x in 1 2 3 4 5 6 7 8 9 10
do
  /usr/bin/time -f "%e" $1 $2 $3 $4 $5
done

echo `date` >> /tmp/lampadas-timer
cat /tmp/lampadas-timer
