insert(linux_os,             1)
insert(system_admin,         2)
insert(hardware,             3)
insert(networking,           4)
insert(installing_apps,      5)
insert(user_apps,            6)
insert(server_apps,          7)
insert(guis_wms,             8)
insert(multimedia,           9)
insert(programming,          10)
insert(languages,            11)
insert(misc,                 12)

