insert(user,        1,  t,  t,  f,  f)
insert(admin,       2,  t,  f,  t,  f)
insert(sysadmin,    3,  t,  f,  f,  t)
insert(main,        4,  f,  f,  f,  f)
insert(news,        5,  f,  f,  f,  f)
insert(volunteer,   6,  f,  f,  f,  f)
insert(help,        7,  f,  f,  f,  f)
