#! /usr/bin/perl

use CGI qw(:standard);

$query = new CGI;

# Read parameters
$doc_id = param('doc_id');

print "Content-Type: text/plain; charset=ISO-8859-1\n\n";

$cmd = "ldp-wiki $doc_id";
system("$cmd");

