#! /usr/bin/perl

use CGI qw(:standard);

$query = new CGI;

# Read parameters
$name = param('name');

print "Content-Type: text/plain; charset=ISO-8859-1\n\n";

$cmd = "ldp-xml -n $name";
system("$cmd");

