#!/usr/bin/perl

use Pg;

$dbmain = "ldp";
@row;

$conn=Pg::connectdb("dbname=$dbmain");
die $conn->errorMessage unless PGRES_CONNECTION_OK eq $conn->status;

#load document meta-data
$docresult = $conn->exec("SELECT doc_id, title FROM document WHERE pub_status='N' AND format='WIKI'");
die $conn->errorMessage unless PGRES_TUPLES_OK eq $docresult->resultStatus;
while (@row = $docresult->fetchrow) {
	$doc_id = $row[0];
	$title = $row[1];
	$wikiresult = $conn->exec("SELECT wiki FROM document_wiki WHERE doc_id = $doc_id ORDER BY revision DESC LIMIT 1, 0");
	die $conn->errorMessage unless PGRES_TUPLES_OK eq $wikiresult->resultStatus;
	while (@wikirow = $wikiresult->fetchrow) {
		$revision	= $revisions + 1;
		$wiki		= $wikirow[0];
		$firstsect = 1;
		foreach (split(/\[\[wiki:/, $wiki)) {
			if ($firstsect) {
				$firstsect = 0;
			} else {
				$link = $_;
				$link =~ s/\]\].*//s;
				print "$link\n";
			}
		}
	}
}
