DELETE FROM language_i18n;
DELETE FROM language;
DELETE FROM string_i18n;
DELETE FROM string;

INSERT INTO language(isocode) values ('AA');
INSERT INTO language(isocode) values ('AB');
INSERT INTO language(isocode) values ('AF');
INSERT INTO language(isocode) values ('AM');
INSERT INTO language(isocode) values ('AR');
INSERT INTO language(isocode) values ('AS');
INSERT INTO language(isocode) values ('AY');
INSERT INTO language(isocode) values ('AZ');
INSERT INTO language(isocode) values ('BA');
INSERT INTO language(isocode) values ('BE');
INSERT INTO language(isocode) values ('BG');
INSERT INTO language(isocode) values ('BH');
INSERT INTO language(isocode) values ('BI');
INSERT INTO language(isocode) values ('BN');
INSERT INTO language(isocode) values ('BO');
INSERT INTO language(isocode) values ('BR');
INSERT INTO language(isocode) values ('CA');
INSERT INTO language(isocode) values ('CO');
INSERT INTO language(isocode) values ('CS');
INSERT INTO language(isocode) values ('CY');
INSERT INTO language(isocode) values ('DA');
INSERT INTO language(isocode) values ('DE');
INSERT INTO language(isocode) values ('DZ');
INSERT INTO language(isocode) values ('EL');
INSERT INTO language(isocode) values ('EN');
INSERT INTO language(isocode) values ('EO');
INSERT INTO language(isocode) values ('ES');
INSERT INTO language(isocode) values ('ET');
INSERT INTO language(isocode) values ('EU');
INSERT INTO language(isocode) values ('FA');
INSERT INTO language(isocode) values ('FI');
INSERT INTO language(isocode) values ('FJ');
INSERT INTO language(isocode) values ('FO');
INSERT INTO language(isocode) values ('FR');
INSERT INTO language(isocode) values ('FY');
INSERT INTO language(isocode) values ('GA');
INSERT INTO language(isocode) values ('GD');
INSERT INTO language(isocode) values ('GL');
INSERT INTO language(isocode) values ('GN');
INSERT INTO language(isocode) values ('GU');
INSERT INTO language(isocode) values ('HA');
INSERT INTO language(isocode) values ('HI');
INSERT INTO language(isocode) values ('HR');
INSERT INTO language(isocode) values ('HU');
INSERT INTO language(isocode) values ('HY');
INSERT INTO language(isocode) values ('IA');
INSERT INTO language(isocode) values ('IE');
INSERT INTO language(isocode) values ('IK');
INSERT INTO language(isocode) values ('IN');
INSERT INTO language(isocode) values ('IS');
INSERT INTO language(isocode) values ('IT');
INSERT INTO language(isocode) values ('IW');
INSERT INTO language(isocode) values ('JA');
INSERT INTO language(isocode) values ('JI');
INSERT INTO language(isocode) values ('JW');
INSERT INTO language(isocode) values ('KA');
INSERT INTO language(isocode) values ('KK');
INSERT INTO language(isocode) values ('KL');
INSERT INTO language(isocode) values ('KM');
INSERT INTO language(isocode) values ('KN');
INSERT INTO language(isocode) values ('KO');
INSERT INTO language(isocode) values ('KS');
INSERT INTO language(isocode) values ('KU');
INSERT INTO language(isocode) values ('KY');
INSERT INTO language(isocode) values ('LA');
INSERT INTO language(isocode) values ('LN');
INSERT INTO language(isocode) values ('LO');
INSERT INTO language(isocode) values ('LT');
INSERT INTO language(isocode) values ('LV');
INSERT INTO language(isocode) values ('MG');
INSERT INTO language(isocode) values ('MI');
INSERT INTO language(isocode) values ('MK');
INSERT INTO language(isocode) values ('ML');
INSERT INTO language(isocode) values ('MN');
INSERT INTO language(isocode) values ('MO');
INSERT INTO language(isocode) values ('MR');
INSERT INTO language(isocode) values ('MS');
INSERT INTO language(isocode) values ('MT');
INSERT INTO language(isocode) values ('MY');
INSERT INTO language(isocode) values ('NA');
INSERT INTO language(isocode) values ('NE');
INSERT INTO language(isocode) values ('NL');
INSERT INTO language(isocode) values ('NO');
INSERT INTO language(isocode) values ('OC');
INSERT INTO language(isocode) values ('OM');
INSERT INTO language(isocode) values ('OR');
INSERT INTO language(isocode) values ('PA');
INSERT INTO language(isocode) values ('PL');
INSERT INTO language(isocode) values ('PS');
INSERT INTO language(isocode) values ('PT');
INSERT INTO language(isocode) values ('QU');
INSERT INTO language(isocode) values ('RM');
INSERT INTO language(isocode) values ('RN');
INSERT INTO language(isocode) values ('RO');
INSERT INTO language(isocode) values ('RU');
INSERT INTO language(isocode) values ('RW');
INSERT INTO language(isocode) values ('SA');
INSERT INTO language(isocode) values ('SD');
INSERT INTO language(isocode) values ('SG');
INSERT INTO language(isocode) values ('SH');
INSERT INTO language(isocode) values ('SI');
INSERT INTO language(isocode) values ('SK');
INSERT INTO language(isocode) values ('SL');
INSERT INTO language(isocode) values ('SM');
INSERT INTO language(isocode) values ('SN');
INSERT INTO language(isocode) values ('SO');
INSERT INTO language(isocode) values ('SQ');
INSERT INTO language(isocode) values ('SR');
INSERT INTO language(isocode) values ('SS');
INSERT INTO language(isocode) values ('ST');
INSERT INTO language(isocode) values ('SU');
INSERT INTO language(isocode) values ('SV');
INSERT INTO language(isocode) values ('SW');
INSERT INTO language(isocode) values ('TA');
INSERT INTO language(isocode) values ('TE');
INSERT INTO language(isocode) values ('TG');
INSERT INTO language(isocode) values ('TH');
INSERT INTO language(isocode) values ('TI');
INSERT INTO language(isocode) values ('TK');
INSERT INTO language(isocode) values ('TL');
INSERT INTO language(isocode) values ('TN');
INSERT INTO language(isocode) values ('TO');
INSERT INTO language(isocode) values ('TR');
INSERT INTO language(isocode) values ('TS');
INSERT INTO language(isocode) values ('TT');
INSERT INTO language(isocode) values ('TW');
INSERT INTO language(isocode) values ('UK');
INSERT INTO language(isocode) values ('UR');
INSERT INTO language(isocode) values ('UZ');
INSERT INTO language(isocode) values ('VI');
INSERT INTO language(isocode) values ('VO');
INSERT INTO language(isocode) values ('WO');
INSERT INTO language(isocode) values ('XH');
INSERT INTO language(isocode) values ('YO');
INSERT INTO language(isocode) values ('ZH');
INSERT INTO language(isocode) values ('ZU');

INSERT INTO language_i18n(isocode, lang, language_name) values ('AA', 'EN', 'Afar');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AB', 'EN', 'Abkhazian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AF', 'EN', 'Afrikaans');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AM', 'EN', 'Amharic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AR', 'EN', 'Arabic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AS', 'EN', 'Assamese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AY', 'EN', 'Aymara');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AZ', 'EN', 'Azerbaijani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BA', 'EN', 'Bashkir');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BE', 'EN', 'Byelorussian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BG', 'EN', 'Bulgarian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BH', 'EN', 'Bihari');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BI', 'EN', 'Bislama');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BN', 'EN', 'Bengali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BO', 'EN', 'Tibetan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BR', 'EN', 'Breton');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CA', 'EN', 'Catalan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CO', 'EN', 'Corsican');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CS', 'EN', 'Czech');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CY', 'EN', 'Welsh');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DA', 'EN', 'Danish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DE', 'EN', 'German');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DZ', 'EN', 'Bhutani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EL', 'EN', 'Greek');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EN', 'EN', 'English');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EO', 'EN', 'Esperanto');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ES', 'EN', 'Spanish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ET', 'EN', 'Estonian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EU', 'EN', 'Basque');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FA', 'EN', 'Persian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FI', 'EN', 'Finnish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FJ', 'EN', 'Fiji');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FO', 'EN', 'Faeroese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FR', 'EN', 'French');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FY', 'EN', 'Frisian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GA', 'EN', 'Irish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GD', 'EN', 'Gaelic (Scots Gaelic)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GL', 'EN', 'Galician');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GN', 'EN', 'Guarani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GU', 'EN', 'Gujarati');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HA', 'EN', 'Hausa');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HI', 'EN', 'Hindi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HR', 'EN', 'Croatian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HU', 'EN', 'Hungarian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HY', 'EN', 'Armenian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IA', 'EN', 'Interlingua');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IE', 'EN', 'Interlingue');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IK', 'EN', 'Inupiak');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IN', 'EN', 'Indonesian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IS', 'EN', 'Icelandic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IT', 'EN', 'Italian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IW', 'EN', 'Hebrew');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JA', 'EN', 'Japanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JI', 'EN', 'Yiddish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JW', 'EN', 'Javanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KA', 'EN', 'Georgian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KK', 'EN', 'Kazakh');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KL', 'EN', 'Greenlandic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KM', 'EN', 'Cambodian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KN', 'EN', 'Kannada');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KO', 'EN', 'Korean');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KS', 'EN', 'Kashmiri');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KU', 'EN', 'Kurdish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KY', 'EN', 'Kirghiz');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LA', 'EN', 'Latin');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LN', 'EN', 'Lingala');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LO', 'EN', 'Laothian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LT', 'EN', 'Lithuanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LV', 'EN', 'Latvian (Lettish)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MG', 'EN', 'Malagasy');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MI', 'EN', 'Maori');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MK', 'EN', 'Macedonian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ML', 'EN', 'Malayalam');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MN', 'EN', 'Mongolian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MO', 'EN', 'Moldavian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MR', 'EN', 'Marathi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MS', 'EN', 'Malay');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MT', 'EN', 'Maltese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MY', 'EN', 'Burmese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NA', 'EN', 'Nauru');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NE', 'EN', 'Nepali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NL', 'EN', 'Dutch');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NO', 'EN', 'Norwegian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OC', 'EN', 'Occitan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OM', 'EN', 'Oromo (Afan)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OR', 'EN', 'Oriya');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PA', 'EN', 'Punjabi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PL', 'EN', 'Polish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PS', 'EN', 'Pashto (Pushto)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PT', 'EN', 'Portuguese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('QU', 'EN', 'Quechua');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RM', 'EN', 'Rhaeto-Romance');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RN', 'EN', 'Kirundi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RO', 'EN', 'Romanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RU', 'EN', 'Russian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RW', 'EN', 'Kinyarwanda');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SA', 'EN', 'Sanskrit');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SD', 'EN', 'Sindhi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SG', 'EN', 'Sangro');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SH', 'EN', 'Serbo-Croatian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SI', 'EN', 'Singhalese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SK', 'EN', 'Slovak');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SL', 'EN', 'Slovenian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SM', 'EN', 'Samoan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SN', 'EN', 'Shona');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SO', 'EN', 'Somali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SQ', 'EN', 'Albanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SR', 'EN', 'Serbian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SS', 'EN', 'Siswati');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ST', 'EN', 'Sesotho');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SU', 'EN', 'Sudanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SV', 'EN', 'Swedish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SW', 'EN', 'Swahili');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TA', 'EN', 'Tamil');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TE', 'EN', 'Tegulu');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TG', 'EN', 'Tajik');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TH', 'EN', 'Thai');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TI', 'EN', 'Tigrinya');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TK', 'EN', 'Turkmen');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TL', 'EN', 'Tagalog');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TN', 'EN', 'Setswana');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TO', 'EN', 'Tonga');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TR', 'EN', 'Turkish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TS', 'EN', 'Tsonga');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TT', 'EN', 'Tatar');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TW', 'EN', 'Twi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UK', 'EN', 'Ukrainian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UR', 'EN', 'Urdu');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UZ', 'EN', 'Uzbek');
INSERT INTO language_i18n(isocode, lang, language_name) values ('VI', 'EN', 'Vietnamese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('VO', 'EN', 'Volapuk');
INSERT INTO language_i18n(isocode, lang, language_name) values ('WO', 'EN', 'Wolof');
INSERT INTO language_i18n(isocode, lang, language_name) values ('XH', 'EN', 'Xhosa');
INSERT INTO language_i18n(isocode, lang, language_name) values ('YO', 'EN', 'Yoruba');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ZH', 'EN', 'Chinese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ZU', 'EN', 'Zulu');

INSERT INTO string(string_id) VALUES (1);
INSERT INTO string(string_id) VALUES (2);
INSERT INTO string(string_id) VALUES (3);

INSERT INTO string(string_id) VALUES (1000);
INSERT INTO string(string_id) VALUES (2000);

INSERT INTO string_i18n(string_id, lang, string) VALUES (1, 'EN', 'Test Text');
INSERT INTO string_i18n(string_id, lang, string) VALUES (2, 'EN', '<h1><center>Lampadas Header</center></h1>');
INSERT INTO string_i18n(string_id, lang, string) VALUES (3, 'EN', '<h1><center>Lampadas Footer</center></h1>');

INSERT INTO string_i18n(string_id, lang, string) VALUES (1000, 'EN', '|header| |body| |footer|');

INSERT INTO string_i18n(string_id, lang, string) VALUES (2000, 'EN', 'Hi, this page will be about Lampadas.');
