DROP TABLE language;

CREATE TABLE language
(
	isocode			CHAR(2),
	language_name		CHAR(60),

	PRIMARY KEY (isocode)
);

INSERT INTO language(isocode, language_name) values ('AA', 'Afar');
INSERT INTO language(isocode, language_name) values ('AB', 'Abkhazian');
INSERT INTO language(isocode, language_name) values ('AF', 'Afrikaans');
INSERT INTO language(isocode, language_name) values ('AM', 'Amharic');
INSERT INTO language(isocode, language_name) values ('AR', 'Arabic');
INSERT INTO language(isocode, language_name) values ('AS', 'Assamese');
INSERT INTO language(isocode, language_name) values ('AY', 'Aymara');
INSERT INTO language(isocode, language_name) values ('AZ', 'Azerbaijani');
INSERT INTO language(isocode, language_name) values ('BA', 'Bashkir');
INSERT INTO language(isocode, language_name) values ('BE', 'Byelorussian');
INSERT INTO language(isocode, language_name) values ('BG', 'Bulgarian');
INSERT INTO language(isocode, language_name) values ('BH', 'Bihari');
INSERT INTO language(isocode, language_name) values ('BI', 'Bislama');
INSERT INTO language(isocode, language_name) values ('BN', 'Bengali');
INSERT INTO language(isocode, language_name) values ('BO', 'Tibetan');
INSERT INTO language(isocode, language_name) values ('BR', 'Breton');
INSERT INTO language(isocode, language_name) values ('CA', 'Catalan');
INSERT INTO language(isocode, language_name) values ('CO', 'Corsican');
INSERT INTO language(isocode, language_name) values ('CS', 'Czech');
INSERT INTO language(isocode, language_name) values ('CY', 'Welsh');
INSERT INTO language(isocode, language_name) values ('DA', 'Danish');
INSERT INTO language(isocode, language_name) values ('DE', 'German');
INSERT INTO language(isocode, language_name) values ('DZ', 'Bhutani');
INSERT INTO language(isocode, language_name) values ('EL', 'Greek');
INSERT INTO language(isocode, language_name) values ('EN', 'English');
INSERT INTO language(isocode, language_name) values ('EO', 'Esperanto');
INSERT INTO language(isocode, language_name) values ('ES', 'Spanish');
INSERT INTO language(isocode, language_name) values ('ET', 'Estonian');
INSERT INTO language(isocode, language_name) values ('EU', 'Basque');
INSERT INTO language(isocode, language_name) values ('FA', 'Persian');
INSERT INTO language(isocode, language_name) values ('FI', 'Finnish');
INSERT INTO language(isocode, language_name) values ('FJ', 'Fiji');
INSERT INTO language(isocode, language_name) values ('FO', 'Faeroese');
INSERT INTO language(isocode, language_name) values ('FR', 'French');
INSERT INTO language(isocode, language_name) values ('FY', 'Frisian');
INSERT INTO language(isocode, language_name) values ('GA', 'Irish');
INSERT INTO language(isocode, language_name) values ('GD', 'Gaelic (Scots Gaelic)');
INSERT INTO language(isocode, language_name) values ('GL', 'Galician');
INSERT INTO language(isocode, language_name) values ('GN', 'Guarani');
INSERT INTO language(isocode, language_name) values ('GU', 'Gujarati');
INSERT INTO language(isocode, language_name) values ('HA', 'Hausa');
INSERT INTO language(isocode, language_name) values ('HI', 'Hindi');
INSERT INTO language(isocode, language_name) values ('HR', 'Croatian');
INSERT INTO language(isocode, language_name) values ('HU', 'Hungarian');
INSERT INTO language(isocode, language_name) values ('HY', 'Armenian');
INSERT INTO language(isocode, language_name) values ('IA', 'Interlingua');
INSERT INTO language(isocode, language_name) values ('IE', 'Interlingue');
INSERT INTO language(isocode, language_name) values ('IK', 'Inupiak');
INSERT INTO language(isocode, language_name) values ('IN', 'Indonesian');
INSERT INTO language(isocode, language_name) values ('IS', 'Icelandic');
INSERT INTO language(isocode, language_name) values ('IT', 'Italian');
INSERT INTO language(isocode, language_name) values ('IW', 'Hebrew');
INSERT INTO language(isocode, language_name) values ('JA', 'Japanese');
INSERT INTO language(isocode, language_name) values ('JI', 'Yiddish');
INSERT INTO language(isocode, language_name) values ('JW', 'Javanese');
INSERT INTO language(isocode, language_name) values ('KA', 'Georgian');
INSERT INTO language(isocode, language_name) values ('KK', 'Kazakh');
INSERT INTO language(isocode, language_name) values ('KL', 'Greenlandic');
INSERT INTO language(isocode, language_name) values ('KM', 'Cambodian');
INSERT INTO language(isocode, language_name) values ('KN', 'Kannada');
INSERT INTO language(isocode, language_name) values ('KO', 'Korean');
INSERT INTO language(isocode, language_name) values ('KS', 'Kashmiri');
INSERT INTO language(isocode, language_name) values ('KU', 'Kurdish');
INSERT INTO language(isocode, language_name) values ('KY', 'Kirghiz');
INSERT INTO language(isocode, language_name) values ('LA', 'Latin');
INSERT INTO language(isocode, language_name) values ('LN', 'Lingala');
INSERT INTO language(isocode, language_name) values ('LO', 'Laothian');
INSERT INTO language(isocode, language_name) values ('LT', 'Lithuanian');
INSERT INTO language(isocode, language_name) values ('LV', 'Latvian (Lettish)');
INSERT INTO language(isocode, language_name) values ('MG', 'Malagasy');
INSERT INTO language(isocode, language_name) values ('MI', 'Maori');
INSERT INTO language(isocode, language_name) values ('MK', 'Macedonian');
INSERT INTO language(isocode, language_name) values ('ML', 'Malayalam');
INSERT INTO language(isocode, language_name) values ('MN', 'Mongolian');
INSERT INTO language(isocode, language_name) values ('MO', 'Moldavian');
INSERT INTO language(isocode, language_name) values ('MR', 'Marathi');
INSERT INTO language(isocode, language_name) values ('MS', 'Malay');
INSERT INTO language(isocode, language_name) values ('MT', 'Maltese');
INSERT INTO language(isocode, language_name) values ('MY', 'Burmese');
INSERT INTO language(isocode, language_name) values ('NA', 'Nauru');
INSERT INTO language(isocode, language_name) values ('NE', 'Nepali');
INSERT INTO language(isocode, language_name) values ('NL', 'Dutch');
INSERT INTO language(isocode, language_name) values ('NO', 'Norwegian');
INSERT INTO language(isocode, language_name) values ('OC', 'Occitan');
INSERT INTO language(isocode, language_name) values ('OM', 'Oromo (Afan)');
INSERT INTO language(isocode, language_name) values ('OR', 'Oriya');
INSERT INTO language(isocode, language_name) values ('PA', 'Punjabi');
INSERT INTO language(isocode, language_name) values ('PL', 'Polish');
INSERT INTO language(isocode, language_name) values ('PS', 'Pashto (Pushto)');
INSERT INTO language(isocode, language_name) values ('PT', 'Portuguese');
INSERT INTO language(isocode, language_name) values ('QU', 'Quechua');
INSERT INTO language(isocode, language_name) values ('RM', 'Rhaeto-Romance');
INSERT INTO language(isocode, language_name) values ('RN', 'Kirundi');
INSERT INTO language(isocode, language_name) values ('RO', 'Romanian');
INSERT INTO language(isocode, language_name) values ('RU', 'Russian');
INSERT INTO language(isocode, language_name) values ('RW', 'Kinyarwanda');
INSERT INTO language(isocode, language_name) values ('SA', 'Sanskrit');
INSERT INTO language(isocode, language_name) values ('SD', 'Sindhi');
INSERT INTO language(isocode, language_name) values ('SG', 'Sangro');
INSERT INTO language(isocode, language_name) values ('SH', 'Serbo-Croatian');
INSERT INTO language(isocode, language_name) values ('SI', 'Singhalese');
INSERT INTO language(isocode, language_name) values ('SK', 'Slovak');
INSERT INTO language(isocode, language_name) values ('SL', 'Slovenian');
INSERT INTO language(isocode, language_name) values ('SM', 'Samoan');
INSERT INTO language(isocode, language_name) values ('SN', 'Shona');
INSERT INTO language(isocode, language_name) values ('SO', 'Somali');
INSERT INTO language(isocode, language_name) values ('SQ', 'Albanian');
INSERT INTO language(isocode, language_name) values ('SR', 'Serbian');
INSERT INTO language(isocode, language_name) values ('SS', 'Siswati');
INSERT INTO language(isocode, language_name) values ('ST', 'Sesotho');
INSERT INTO language(isocode, language_name) values ('SU', 'Sudanese');
INSERT INTO language(isocode, language_name) values ('SV', 'Swedish');
INSERT INTO language(isocode, language_name) values ('SW', 'Swahili');
INSERT INTO language(isocode, language_name) values ('TA', 'Tamil');
INSERT INTO language(isocode, language_name) values ('TE', 'Tegulu');
INSERT INTO language(isocode, language_name) values ('TG', 'Tajik');
INSERT INTO language(isocode, language_name) values ('TH', 'Thai');
INSERT INTO language(isocode, language_name) values ('TI', 'Tigrinya');
INSERT INTO language(isocode, language_name) values ('TK', 'Turkmen');
INSERT INTO language(isocode, language_name) values ('TL', 'Tagalog');
INSERT INTO language(isocode, language_name) values ('TN', 'Setswana');
INSERT INTO language(isocode, language_name) values ('TO', 'Tonga');
INSERT INTO language(isocode, language_name) values ('TR', 'Turkish');
INSERT INTO language(isocode, language_name) values ('TS', 'Tsonga');
INSERT INTO language(isocode, language_name) values ('TT', 'Tatar');
INSERT INTO language(isocode, language_name) values ('TW', 'Twi');
INSERT INTO language(isocode, language_name) values ('UK', 'Ukrainian');
INSERT INTO language(isocode, language_name) values ('UR', 'Urdu');
INSERT INTO language(isocode, language_name) values ('UZ', 'Uzbek');
INSERT INTO language(isocode, language_name) values ('VI', 'Vietnamese');
INSERT INTO language(isocode, language_name) values ('VO', 'Volapuk');
INSERT INTO language(isocode, language_name) values ('WO', 'Wolof');
INSERT INTO language(isocode, language_name) values ('XH', 'Xhosa');
INSERT INTO language(isocode, language_name) values ('YO', 'Yoruba');
INSERT INTO language(isocode, language_name) values ('ZH', 'Chinese');
INSERT INTO language(isocode, language_name) values ('ZU', 'Zulu');

