=head1 NAME

B<wt2db> - converts WikiText documents into DocBook XML/SGML.


=head1 SYNOPSIS

B<wt2db> [I<OPTION>] [I<FILE>]


=head1 DESCRIPTION

B<wt2db> converts a text file in a special format similar to that used
in WikiWikiWebs into DocBook XML/SGML.
The DocBook it writes out by default is only
a fragment, but it will write a complete document upon request.

By default it reads from STDIN and writes to STDOUT. However, if given a
filename, it will read that file, and an output filename can also be
specified as a command-line option.


=head1 OPTIONS

B<-x>, B<--xml> add XML DOCTYPE and article tags.

B<-s>, B<--sgml> add SGML DOCTYPE and article tags.

B<-n>, B<--nonet> do not access the network.

B<-o>, B<--output-to> I<filename> write to the specified file.

B<-v>, B<--verbose> show diagnostic output.

B<-V>, B<--version> show program version.

B<-h>, B<--help> show a usage message.


=head1 NOTES

B<wt2db> was developed to provide an easier way to write
DocBook documentation.

WikiText is based on the form of text that is used in a
WikiWikiWeb. It provides very simple and easy to remember
tags so you can write a Wiki article without learning HTML.
B<wt2db> was originally written to convert Wikipedia articles
into DocBook.

The Wiki format has been enhanced in several ways to make it
more powerful for authors. Support has been added for Wiki tags
that don't exist in any real Wiki, by giving common DocBook
elements their own Wiki tags. Support has also been added
for including DocBook elements right in the source file.

This means WikiText is a merging of DocBook into a plain text file.
In in its simplest form, it is plain text. A plain text
document can be processed by B<wt2db> and converted into
DocBook.
Or, a complete and valid DocBook document can be processed,
and will pass through the B<w2db> filters and come out
unchanged.
Virtually any combination of DocBook with plain text will work,
with the additional Wiki style tags to make things even easier
for authors.
It put all of the semantic of DocBook
at your disposal, while being as easy to write as a Wiki page.


=head1 WIKITEXT

These are the tags which are supported in this release of
B<wt2db>. All DocBook tags are also supported. If you encounter
any valid DocBook that is not handled correctly, please file
a bug report.

 Foo                    <para>Foo</para>

 =Title=                <sect1>
                            <title>Title</title>
                        </sect1>

 =Title|id=             <sect1 id='id'>
                            <title>Title</title>
                        </sect1>

The id attribute, delimited with a pipe character,
works for other sect levels as well, and many other
tags. In some cases it is not an id value, but the
title, depending on the semantics of the particular
tag. Usage should be obvious in context.

 ==Title==              <sect2>
                            <title>Title</title>
                        </sect2>

 ===Title===            <sect3>
                            <title>Title</title>
                        </sect3>

 #Foo                   <orderedlist>
 #Bar                       <listitem>
 #Baz                           <para>Foo</para>
 /#                         </listitem>
                            <listitem>
                                <para>Bar</para>
                            </listitem>
                            <listitem>
                                <para>Baz</para>
                            </listitem>
                        </orderedlist>

 *Foo                   <simplelist>
 *Bar                       <listitem>
 *Baz                           <para>Foo</para>
 /*                         </listitem>
                            <listitem>
                                <para>Bar</para>
                            </listitem>
                            <listitem>
                                <para>Baz</para>
                            </listitem>
                        </simplelist>

 [[foo]]                <xref linkend='foo' linkterm='foo'/>
 [[link:Foo]]

 [[file:/dev/foo]]      <filename>/dev/foo</filename>


 [[http://foo.org]]     <ulink url='http://foo.org'>
                            <citetitle>http://foo.org</citetitle>
                        </ulink>

 [[http://foo.org Foo]] <ulink url='http://foo.org'>
 [[http://foo.org|Foo]]     <citetitle>Foo</citetitle>
                        </ulink>

 '''Foo'''              <emphasis>Foo</emphasis>

A few DocBook structures will not have <para> tags wrapped around them. They
are <para> itself, <sect?> and <programlisting>. If you insert anything
using these tags, no <para> tags will be wrapped around it or inserted into it.
So if you want fine control over your <para> tags, insert them yourself.

The <screen> element will be wrapped with <para> tags, but no internal
paragraph breaks will be generated.


=head1 RESTRICTIONS

Currently only a single form of WikiText is supported, which is very
similar to that used by the Wikipedia (see http://www.wikipedia.com).
A future release will be configurable to support additional styles of
WikiText.


=head1 BUGS

Bugs are tracked in the SourceForge project page at:

http://www.sourceforge.net/projects/linuxdoc

If you report a bug in B<wt2db>, specify wt2db as the category so it will
be routed the appropriate person.


=head1 SEE ALSO

See the home page of the Linux Documentation Project,
http://www.tldp.org for updates and more information.


=head1 AUTHOR

This man page was written by David C. Merrill <david@lupercalia.net>.

Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU Free Documentation License, Version 1.1 or any later
version published by the Free Software Foundation; with no Invariant Sections,
no Front-Cover Texts and no Back-Cover Texts.

=cut

