#!/bin/bash
#
# Packager for ScrollServer
#
# All files in scrollserver/ will be built into a tar archive
# except for CVS directories and the pub directory.
#
# Pass the version number on the command line.

VERSION="$1"
ROOTDIR="../.."
PACKAGEDIR="pub"

if [ "$VERSION" = "" ]
then
  echo "Usage: package <version>"
  exit
fi

cd $ROOTDIR

TARFILE="scrollserver-$VERSION.tar"
BZFILE="$TARFILE.bz2"

echo "Creating $BZFILE"			# Do not include CVS, pub or temp dirs
tar -cf $TARFILE scrollserver --exclude=CVS --exclude=pub --exclude=temp

if [ -f scrollserver/$PACKAGEDIR/$BZFILE ]
then
  rm scrollserver/$PACKAGEDIR/$BZFILE
fi

mv $TARFILE scrollserver/$PACKAGEDIR/$TARFILE
bzip2 scrollserver/$PACKAGEDIR/$TARFILE
