insert(201, [german], [author], [david@lupercalia.net], [t])
insert(202, [german], [author], [david@lupercalia.net], [t])
insert(203, [german], [author], [david@lupercalia.net], [t])
insert(204, [german], [author], [david@lupercalia.net], [t])
insert(205, [german], [author], [david@lupercalia.net], [t])
