#!/usr/bin/perl
#
# replace iso-8859-2 characters with appropriate SGML entities
# author: Juraj Bednar
# usage: lat2ent.pl <latin2.sgml >entities.sgml

while ($_=<>) {
s/¡/&Aogon;/g;
s/£/&Lstrok;/g;
s/¥/&Lcaron;/g;
s/¦/&Sacute;/g;
s/©/&Scaron;/g;
s/ª/&Scedil;/g;
s/«/&Tcaron;/g;
s/¬/&Zacute;/g;
s/®/&Zcaron;/g;
s/¯/&Zabovedot;/g;
s/±/&aogon;/g;
s/³/&lstrok;/g;
s/µ/&lcaron;/g;
s/¶/&sacute;/g;
s/¹/&scaron;/g;
s/º/&scedil;/g;
s/»/&tcaron;/g;
s/¼/&zacute;/g;
s/¾/&zcaron;/g;
s/¿/&zabovedot;/g;
s/À/&Racute;/g;
s/Á/&Aacute;/g;
s/Â/&Acirc;/g;
s/Ã/&Abreve;/g;
s/Ä/&Amacr;/g;
s/Å/&Lacute;/g;
s/Æ/&Cacute;/g;
s/Ç/&Ccedil;/g;
s/È/&Ccaron;/g;
s/É/&Eacute;/g;
s/Ê/&Eogon;/g;
s/Ë/&Emacr;/g;
s/Ì/&Ecaron;/g;
s/Í/&Iacute;/g;
s/Î/&Icirc;/g;
s/Ï/&Dcaron;/g;
s/Ñ/&Nacute;/g;
s/Ò/&Ncaron;/g;
s/Ó/&Oacute;/g;
s/Ô/&Ocirc;/g;
s/Õ/&Odblac;/g;
s/Ö/&Omacr;/g;
s/Ø/&Rcaron;/g;
s/Ù/&Uring;/g;
s/Ú/&Uacute;/g;
s/Û/&Udblac;/g;
s/Ü/&Umacr;/g;
s/Ý/&Yacute;/g;
s/Þ/&Tcedil;/g;
s/ß/&ssharp;/g;
s/à/&racute;/g;
s/á/&aacute;/g;
s/â/&acirc;/g;
s/ã/&abreve;/g;
s/ä/&amacr;/g;
s/å/&lacute;/g;
s/æ/&cacute;/g;
s/ç/&ccedil;/g;
s/è/&ccaron;/g;
s/é/&eacute;/g;
s/ê/&eogon;/g;
s/ë/&emacr;/g;
s/ì/&ecaron;/g;
s/í/&iacute;/g;
s/î/&icirc;/g;
s/ï/&dcaron;/g;
s/ñ/&nacute;/g;
s/ò/&ncaron;/g;
s/ó/&oacute;/g;
s/ô/&ocirc;/g;
s/õ/&odblac;/g;
s/ö/&omacr;/g;
s/ø/&rcaron;/g;
s/ù/&uring;/g;
s/ú/&uacute;/g;
s/û/&udblac;/g;
s/ü/&umacr;/g;
s/ý/&yacute;/g;
s/þ/&tcedil;/g;
print $_;
}
