#!/usr/bin/perl

use CGI qw(:standard);

$query = new CGI;

# Read parameters
$name = param('name');
$name =~ s/\s+$//;

print "Content-Type: text/plain; charset=ISO-8859-1\n\n";

if ($name) {
	$cmd = "/usr/local/bin/ldp-omf -n $name";
} else {
	$cmd = "/usr/local/bin/ldp-omf";
}
system("$cmd");

