### Pick a compiler:
CC := gcc-3.0
# CC := colorgcc
# CC := gcc

WARN    := -W -Wall
INCLUDE := -isystem /lib/modules/`uname -r`/build/include
CFLAGS  := -O2 -DMODULE -D__KERNEL__ ${WARN} ${INCLUDE}
OBJS    := ${patsubst %.c, %.o, ${wildcard *.c}}

all: ${OBJS}

.PHONY: clean

clean:
	rm -rf *.o
