CREATE TABLE document
(
	doc_id			INT4		NOT NULL,
	lang			CHAR(2)		NOT NULL	REFERENCES language(lang_code),
	title			TEXT,
	short_title		TEXT,
	type_code		CHAR(20)			REFERENCES type(type_code),
	format_code		CHAR(20)			REFERENCES format(format_code),
	dtd_code		CHAR(12)			REFERENCES dtd(dtd_code),
	dtd_version		CHAR(12),
	version			CHAR(12),
	last_update		DATE,
	ISBN			TEXT,
	pub_status_code		CHAR				REFERENCES pub_status(pub_status_code),
	review_status_code	CHAR				REFERENCES review_status(review_status_code),
	tickle_date		DATE,
	pub_date		DATE,
	tech_review_status_code	CHAR				REFERENCES review_status(review_status_code),
	maintained		BOOLEAN		DEFAULT False,
	maintainer_wanted	BOOLEAN		DEFAULT False,
	license_code		CHAR(12)			REFERENCES license(license_code),
	license_version		CHAR(12),
	copyright_holder	TEXT,
	abstract		TEXT,
	short_desc		TEXT,
	rating			REAL,
	sk_seriesid		CHAR(36)	NOT NULL,
	replaced_by_id		INT4,
	pub_time		TIMESTAMP,
	mirror_time		TIMESTAMP,

	PRIMARY KEY (doc_id)
);
