#!/usr/bin/perl -ws
# Installation and operation of lampadas must not require perl.
# For this reason character set conversion is implemented with sed.
# This script generates both input and output filter. 
#
# To generate a input filter:          ./ISO-8859-15.pl
# To generate a output filter:         ./ISO-8859-15.pl -output
# To generate a HTML page of input:    ./ISO-8859-15.pl -html

use strict;

$::html = 0 if (!defined($::html));
$::output = 0 if (!defined($::output));

my $name = 'ISO-8859-15';

my %entity = (
  'aacute' => 0x00E1,
  'Aacute' => 0x00C1,
  'acirc' => 0x00E2,
  'Acirc' => 0x00C2,
  'agrave' => 0x00E0,
  'Agrave' => 0x00C0,
  'aring' => 0x00E5,
  'Aring' => 0x00C5,
  'atilde' => 0x00E3,
  'Atilde' => 0x00C3,
  'auml' => 0x00E4,
  'Auml' => 0x00C4,
  'aelig' => 0x00E6,
  'AElig' => 0x00C6,
  'ccedil' => 0x00E7,
  'Ccedil' => 0x00C7,
  'eth' => 0x00F0,
  'ETH' => 0x00D0,
  'eacute' => 0x00E9,
  'Eacute' => 0x00C9,
  'ecirc' => 0x00EA,
  'Ecirc' => 0x00CA,
  'egrave' => 0x00E8,
  'Egrave' => 0x00C8,
  'euml' => 0x00EB,
  'Euml' => 0x00CB,
  'iacute' => 0x00ED,
  'Iacute' => 0x00CD,
  'icirc' => 0x00EE,
  'Icirc' => 0x00CE,
  'igrave' => 0x00EC,
  'Igrave' => 0x00CC,
  'iuml' => 0x00EF,
  'Iuml' => 0x00CF,
  'ntilde' => 0x00F1,
  'Ntilde' => 0x00D1,
  'oacute' => 0x00F3,
  'Oacute' => 0x00D3,
  'ocirc' => 0x00F4,
  'Ocirc' => 0x00D4,
  'ograve' => 0x00F2,
  'Ograve' => 0x00D2,
  'oslash' => 0x00F8,
  'Oslash' => 0x00D8,
  'otilde' => 0x00F5,
  'Otilde' => 0x00D5,
  'ouml' => 0x00F6,
  'Ouml' => 0x00D6,
  'szlig' => 0x00DF,
  'thorn' => 0x00FE,
  'THORN' => 0x00DE,
  'uacute' => 0x00FA,
  'Uacute' => 0x00DA,
  'ucirc' => 0x00FB,
  'Ucirc' => 0x00DB,
  'ugrave' => 0x00F9,
  'Ugrave' => 0x00D9,
  'uuml' => 0x00FC,
  'Uuml' => 0x00DC,
  'yacute' => 0x00FD,
  'Yacute' => 0x00DD,
  'yuml' => 0x00FF
);

if ($::html)
{
  print "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\">\n";
  print "<html><head>\n";
  print "<meta HTTP-EQUIV=\"Content-Type\" ";
  print "CONTENT=\"text/html; charset=$name\">\n";
  print "</head><body><pre>\n";
}

print "#!/bin/sed -f\n\n";
print "# Generated by $name.pl. Do not modify.\n";
if ($::output)
{
  print "# Translation of HTML entities to $name. ";
  print "Applied on output of psql.\n\n";
  for my $entity(keys %entity)
  {
    my $code = $entity{$entity};
    printf  "s/\\&%s;/%c/g\n", $entity, $code;
  }
}
else
{
  print "# Translation of $name to HTML entities. ";
  print "Applied on input of psql.\n\n";
  for my $entity(keys %entity)
  {
    my $code = $entity{$entity};
    printf  "s/%c/\\&%s;/g\n", $code, $entity;
  }
}
print "</pre></body></html>\n" if ($::html);
