DELETE FROM language_i18n;
DELETE FROM language;

INSERT INTO language(isocode, supported) values ('AA', 'f');
INSERT INTO language(isocode, supported) values ('AB', 'f');
INSERT INTO language(isocode, supported) values ('AF', 'f');
INSERT INTO language(isocode, supported) values ('AM', 'f');
INSERT INTO language(isocode, supported) values ('AR', 'f');
INSERT INTO language(isocode, supported) values ('AS', 'f');
INSERT INTO language(isocode, supported) values ('AY', 'f');
INSERT INTO language(isocode, supported) values ('AZ', 'f');
INSERT INTO language(isocode, supported) values ('BA', 'f');
INSERT INTO language(isocode, supported) values ('BE', 'f');
INSERT INTO language(isocode, supported) values ('BG', 'f');
INSERT INTO language(isocode, supported) values ('BH', 'f');
INSERT INTO language(isocode, supported) values ('BI', 'f');
INSERT INTO language(isocode, supported) values ('BN', 'f');
INSERT INTO language(isocode, supported) values ('BO', 'f');
INSERT INTO language(isocode, supported) values ('BR', 'f');
INSERT INTO language(isocode, supported) values ('CA', 'f');
INSERT INTO language(isocode, supported) values ('CO', 'f');
INSERT INTO language(isocode, supported) values ('CS', 'f');
INSERT INTO language(isocode, supported) values ('CY', 'f');
INSERT INTO language(isocode, supported) values ('DA', 'f');
INSERT INTO language(isocode, supported) values ('DE', 'f');
INSERT INTO language(isocode, supported) values ('DZ', 'f');
INSERT INTO language(isocode, supported) values ('EL', 'f');
INSERT INTO language(isocode, supported) values ('EN', 't');
INSERT INTO language(isocode, supported) values ('EO', 'f');
INSERT INTO language(isocode, supported) values ('ES', 'f');
INSERT INTO language(isocode, supported) values ('ET', 'f');
INSERT INTO language(isocode, supported) values ('EU', 'f');
INSERT INTO language(isocode, supported) values ('FA', 'f');
INSERT INTO language(isocode, supported) values ('FI', 'f');
INSERT INTO language(isocode, supported) values ('FJ', 'f');
INSERT INTO language(isocode, supported) values ('FO', 'f');
INSERT INTO language(isocode, supported) values ('FR', 't');
INSERT INTO language(isocode, supported) values ('FY', 'f');
INSERT INTO language(isocode, supported) values ('GA', 'f');
INSERT INTO language(isocode, supported) values ('GD', 'f');
INSERT INTO language(isocode, supported) values ('GL', 'f');
INSERT INTO language(isocode, supported) values ('GN', 'f');
INSERT INTO language(isocode, supported) values ('GU', 'f');
INSERT INTO language(isocode, supported) values ('HA', 'f');
INSERT INTO language(isocode, supported) values ('HI', 'f');
INSERT INTO language(isocode, supported) values ('HR', 'f');
INSERT INTO language(isocode, supported) values ('HU', 'f');
INSERT INTO language(isocode, supported) values ('HY', 'f');
INSERT INTO language(isocode, supported) values ('IA', 'f');
INSERT INTO language(isocode, supported) values ('IE', 'f');
INSERT INTO language(isocode, supported) values ('IK', 'f');
INSERT INTO language(isocode, supported) values ('IN', 'f');
INSERT INTO language(isocode, supported) values ('IS', 'f');
INSERT INTO language(isocode, supported) values ('IT', 'f');
INSERT INTO language(isocode, supported) values ('IW', 'f');
INSERT INTO language(isocode, supported) values ('JA', 'f');
INSERT INTO language(isocode, supported) values ('JI', 'f');
INSERT INTO language(isocode, supported) values ('JW', 'f');
INSERT INTO language(isocode, supported) values ('KA', 'f');
INSERT INTO language(isocode, supported) values ('KK', 'f');
INSERT INTO language(isocode, supported) values ('KL', 'f');
INSERT INTO language(isocode, supported) values ('KM', 'f');
INSERT INTO language(isocode, supported) values ('KN', 'f');
INSERT INTO language(isocode, supported) values ('KO', 'f');
INSERT INTO language(isocode, supported) values ('KS', 'f');
INSERT INTO language(isocode, supported) values ('KU', 'f');
INSERT INTO language(isocode, supported) values ('KY', 'f');
INSERT INTO language(isocode, supported) values ('LA', 'f');
INSERT INTO language(isocode, supported) values ('LN', 'f');
INSERT INTO language(isocode, supported) values ('LO', 'f');
INSERT INTO language(isocode, supported) values ('LT', 'f');
INSERT INTO language(isocode, supported) values ('LV', 'f');
INSERT INTO language(isocode, supported) values ('MG', 'f');
INSERT INTO language(isocode, supported) values ('MI', 'f');
INSERT INTO language(isocode, supported) values ('MK', 'f');
INSERT INTO language(isocode, supported) values ('ML', 'f');
INSERT INTO language(isocode, supported) values ('MN', 'f');
INSERT INTO language(isocode, supported) values ('MO', 'f');
INSERT INTO language(isocode, supported) values ('MR', 'f');
INSERT INTO language(isocode, supported) values ('MS', 'f');
INSERT INTO language(isocode, supported) values ('MT', 'f');
INSERT INTO language(isocode, supported) values ('MY', 'f');
INSERT INTO language(isocode, supported) values ('NA', 'f');
INSERT INTO language(isocode, supported) values ('NE', 'f');
INSERT INTO language(isocode, supported) values ('NL', 'f');
INSERT INTO language(isocode, supported) values ('NO', 'f');
INSERT INTO language(isocode, supported) values ('OC', 'f');
INSERT INTO language(isocode, supported) values ('OM', 'f');
INSERT INTO language(isocode, supported) values ('OR', 'f');
INSERT INTO language(isocode, supported) values ('PA', 'f');
INSERT INTO language(isocode, supported) values ('PL', 'f');
INSERT INTO language(isocode, supported) values ('PS', 'f');
INSERT INTO language(isocode, supported) values ('PT', 'f');
INSERT INTO language(isocode, supported) values ('QU', 'f');
INSERT INTO language(isocode, supported) values ('RM', 'f');
INSERT INTO language(isocode, supported) values ('RN', 'f');
INSERT INTO language(isocode, supported) values ('RO', 'f');
INSERT INTO language(isocode, supported) values ('RU', 'f');
INSERT INTO language(isocode, supported) values ('RW', 'f');
INSERT INTO language(isocode, supported) values ('SA', 'f');
INSERT INTO language(isocode, supported) values ('SD', 'f');
INSERT INTO language(isocode, supported) values ('SG', 'f');
INSERT INTO language(isocode, supported) values ('SH', 'f');
INSERT INTO language(isocode, supported) values ('SI', 'f');
INSERT INTO language(isocode, supported) values ('SK', 'f');
INSERT INTO language(isocode, supported) values ('SL', 'f');
INSERT INTO language(isocode, supported) values ('SM', 'f');
INSERT INTO language(isocode, supported) values ('SN', 'f');
INSERT INTO language(isocode, supported) values ('SO', 'f');
INSERT INTO language(isocode, supported) values ('SQ', 'f');
INSERT INTO language(isocode, supported) values ('SR', 'f');
INSERT INTO language(isocode, supported) values ('SS', 'f');
INSERT INTO language(isocode, supported) values ('ST', 'f');
INSERT INTO language(isocode, supported) values ('SU', 'f');
INSERT INTO language(isocode, supported) values ('SV', 'f');
INSERT INTO language(isocode, supported) values ('SW', 'f');
INSERT INTO language(isocode, supported) values ('TA', 'f');
INSERT INTO language(isocode, supported) values ('TE', 'f');
INSERT INTO language(isocode, supported) values ('TG', 'f');
INSERT INTO language(isocode, supported) values ('TH', 'f');
INSERT INTO language(isocode, supported) values ('TI', 'f');
INSERT INTO language(isocode, supported) values ('TK', 'f');
INSERT INTO language(isocode, supported) values ('TL', 'f');
INSERT INTO language(isocode, supported) values ('TN', 'f');
INSERT INTO language(isocode, supported) values ('TO', 'f');
INSERT INTO language(isocode, supported) values ('TR', 'f');
INSERT INTO language(isocode, supported) values ('TS', 'f');
INSERT INTO language(isocode, supported) values ('TT', 'f');
INSERT INTO language(isocode, supported) values ('TW', 'f');
INSERT INTO language(isocode, supported) values ('UK', 'f');
INSERT INTO language(isocode, supported) values ('UR', 'f');
INSERT INTO language(isocode, supported) values ('UZ', 'f');
INSERT INTO language(isocode, supported) values ('VI', 'f');
INSERT INTO language(isocode, supported) values ('VO', 'f');
INSERT INTO language(isocode, supported) values ('WO', 'f');
INSERT INTO language(isocode, supported) values ('XH', 'f');
INSERT INTO language(isocode, supported) values ('YO', 'f');
INSERT INTO language(isocode, supported) values ('ZH', 'f');
INSERT INTO language(isocode, supported) values ('ZU', 'f');

INSERT INTO language_i18n(isocode, lang, language_name) values ('AA', 'EN', 'Afar');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AB', 'EN', 'Abkhazian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AF', 'EN', 'Afrikaans');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AM', 'EN', 'Amharic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AR', 'EN', 'Arabic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AS', 'EN', 'Assamese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AY', 'EN', 'Aymara');
INSERT INTO language_i18n(isocode, lang, language_name) values ('AZ', 'EN', 'Azerbaijani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BA', 'EN', 'Bashkir');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BE', 'EN', 'Byelorussian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BG', 'EN', 'Bulgarian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BH', 'EN', 'Bihari');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BI', 'EN', 'Bislama');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BN', 'EN', 'Bengali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BO', 'EN', 'Tibetan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('BR', 'EN', 'Breton');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CA', 'EN', 'Catalan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CO', 'EN', 'Corsican');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CS', 'EN', 'Czech');
INSERT INTO language_i18n(isocode, lang, language_name) values ('CY', 'EN', 'Welsh');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DA', 'EN', 'Danish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DE', 'EN', 'German');
INSERT INTO language_i18n(isocode, lang, language_name) values ('DZ', 'EN', 'Bhutani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EL', 'EN', 'Greek');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EN', 'EN', 'English');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EO', 'EN', 'Esperanto');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ES', 'EN', 'Spanish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ET', 'EN', 'Estonian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('EU', 'EN', 'Basque');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FA', 'EN', 'Persian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FI', 'EN', 'Finnish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FJ', 'EN', 'Fiji');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FO', 'EN', 'Faeroese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FR', 'EN', 'French');
INSERT INTO language_i18n(isocode, lang, language_name) values ('FY', 'EN', 'Frisian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GA', 'EN', 'Irish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GD', 'EN', 'Gaelic (Scots Gaelic)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GL', 'EN', 'Galician');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GN', 'EN', 'Guarani');
INSERT INTO language_i18n(isocode, lang, language_name) values ('GU', 'EN', 'Gujarati');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HA', 'EN', 'Hausa');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HI', 'EN', 'Hindi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HR', 'EN', 'Croatian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HU', 'EN', 'Hungarian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('HY', 'EN', 'Armenian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IA', 'EN', 'Interlingua');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IE', 'EN', 'Interlingue');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IK', 'EN', 'Inupiak');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IN', 'EN', 'Indonesian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IS', 'EN', 'Icelandic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IT', 'EN', 'Italian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('IW', 'EN', 'Hebrew');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JA', 'EN', 'Japanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JI', 'EN', 'Yiddish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('JW', 'EN', 'Javanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KA', 'EN', 'Georgian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KK', 'EN', 'Kazakh');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KL', 'EN', 'Greenlandic');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KM', 'EN', 'Cambodian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KN', 'EN', 'Kannada');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KO', 'EN', 'Korean');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KS', 'EN', 'Kashmiri');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KU', 'EN', 'Kurdish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('KY', 'EN', 'Kirghiz');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LA', 'EN', 'Latin');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LN', 'EN', 'Lingala');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LO', 'EN', 'Laothian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LT', 'EN', 'Lithuanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('LV', 'EN', 'Latvian (Lettish)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MG', 'EN', 'Malagasy');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MI', 'EN', 'Maori');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MK', 'EN', 'Macedonian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ML', 'EN', 'Malayalam');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MN', 'EN', 'Mongolian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MO', 'EN', 'Moldavian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MR', 'EN', 'Marathi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MS', 'EN', 'Malay');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MT', 'EN', 'Maltese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('MY', 'EN', 'Burmese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NA', 'EN', 'Nauru');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NE', 'EN', 'Nepali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NL', 'EN', 'Dutch');
INSERT INTO language_i18n(isocode, lang, language_name) values ('NO', 'EN', 'Norwegian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OC', 'EN', 'Occitan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OM', 'EN', 'Oromo (Afan)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('OR', 'EN', 'Oriya');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PA', 'EN', 'Punjabi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PL', 'EN', 'Polish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PS', 'EN', 'Pashto (Pushto)');
INSERT INTO language_i18n(isocode, lang, language_name) values ('PT', 'EN', 'Portuguese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('QU', 'EN', 'Quechua');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RM', 'EN', 'Rhaeto-Romance');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RN', 'EN', 'Kirundi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RO', 'EN', 'Romanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RU', 'EN', 'Russian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('RW', 'EN', 'Kinyarwanda');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SA', 'EN', 'Sanskrit');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SD', 'EN', 'Sindhi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SG', 'EN', 'Sangro');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SH', 'EN', 'Serbo-Croatian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SI', 'EN', 'Singhalese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SK', 'EN', 'Slovak');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SL', 'EN', 'Slovenian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SM', 'EN', 'Samoan');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SN', 'EN', 'Shona');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SO', 'EN', 'Somali');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SQ', 'EN', 'Albanian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SR', 'EN', 'Serbian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SS', 'EN', 'Siswati');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ST', 'EN', 'Sesotho');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SU', 'EN', 'Sudanese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SV', 'EN', 'Swedish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('SW', 'EN', 'Swahili');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TA', 'EN', 'Tamil');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TE', 'EN', 'Tegulu');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TG', 'EN', 'Tajik');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TH', 'EN', 'Thai');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TI', 'EN', 'Tigrinya');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TK', 'EN', 'Turkmen');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TL', 'EN', 'Tagalog');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TN', 'EN', 'Setswana');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TO', 'EN', 'Tonga');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TR', 'EN', 'Turkish');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TS', 'EN', 'Tsonga');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TT', 'EN', 'Tatar');
INSERT INTO language_i18n(isocode, lang, language_name) values ('TW', 'EN', 'Twi');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UK', 'EN', 'Ukrainian');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UR', 'EN', 'Urdu');
INSERT INTO language_i18n(isocode, lang, language_name) values ('UZ', 'EN', 'Uzbek');
INSERT INTO language_i18n(isocode, lang, language_name) values ('VI', 'EN', 'Vietnamese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('VO', 'EN', 'Volapuk');
INSERT INTO language_i18n(isocode, lang, language_name) values ('WO', 'EN', 'Wolof');
INSERT INTO language_i18n(isocode, lang, language_name) values ('XH', 'EN', 'Xhosa');
INSERT INTO language_i18n(isocode, lang, language_name) values ('YO', 'EN', 'Yoruba');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ZH', 'EN', 'Chinese');
INSERT INTO language_i18n(isocode, lang, language_name) values ('ZU', 'EN', 'Zulu');
