insert([hostname], [])
insert([smtp_server], [])
insert([local_email], [])
insert([cookie_domain], [])
insert([copyright], [Copyright &copy; A. Random Hacker])
insert([project], [Your Project Name])
insert([project_short], [YPN])
insert([root_dir], [/])
insert([cvs_root], [/var/cache/lampadas/])
insert([version], [0.2])
