#!/bin/bash
rm -rf /home/httpd/html/tmp/PLD-Guide
umask 022
cp -r /home/users/ser/PLD-Guide /home/httpd/html/tmp
cd /home/httpd/html/tmp/PLD-Guide; docbook2html PLD-Guide.xml
chmod -R a+rX /home/httpd/html/tmp/PLD-Guide
