#!/usr/bin/perl
#
#Converts txt files into docbook.
#
$VERION = '0.2';

use Wt2Db;
$WT2DB = new Wt2Db;

my $txtfile = '';
my $dbfile = '';
my $verbose = 0;
my $error = 0;

# read in cmd-line arguments
#
while (1) {
	if($ARGV[0] eq "-o" or $ARGV[0] eq "--output-to") {
		shift(@ARGV);
		$dbfile = $ARGV[0];
		shift(@ARGV);
	} elsif($ARGV[0] eq "-h" or $ARGV[0] eq "--help") {
		$WT2DB->Usage();
	} elsif($ARGV[0] eq "-v" or $ARGV[0] eq "--verbose") {
		$verbose++;
		shift(@ARGV);
	} else {
		$txtfile = $ARGV[0];
		shift(@ARGV);
	}

	if ($ARGV[0] eq '') {
		last;
	}
}

$WT2DB->ProcessFile($txtfile, $dbfile, $verbose);
